### ISSUE TITLE
"Click on the image to see the 3 minutes" - the image is not showing

### ISSUE THREAD

**Issue by AlexKurek** [vpicouet/pyds9plugin#3]
**Describe the bug**
"Click on the image to see the 3 minutes [...]" - the image is not showing after this text, just a blank space.

**Comment by vpicouet** [comment]
I'll solve that soon, in the meanwhile you can see it here: https://vpicouet.github.io/pyds9plugin-doc/

**Comment by vpicouet** [comment]
That's corrected, thanks for the info
